### ISSUE TITLE
Feat Request: Option to add custom source for GitHub Enterprise

### ISSUE THREAD

**Issue by GeorgeWL** [OctoLinker/OctoLinker#1453] opened 2022-01-18 14:58 UTC
I uninstalled it because I want to use it on a privately hosted GitHub Enterprise server, but there's no easy way to add that as a source

**Comment by xt0rted** [comment] 2022-01-19 18:36
Thanks for the feature request. This is being tracked in #75.

Duplicate of #12

**Closed by xt0rted** 2022-01-19 18:36 UTC
