### ISSUE TITLE
Not working on the beta

### ISSUE THREAD

**Issue by AngeloCore** [OctoLinker/OctoLinker#1755] opened 2023-01-29 16:02 UTC
### Expected Behavior

It should link deps

### What actually happened?

Nothing changed

### URL

Every repo

### Anything else we should know?

I am talking about this version:
![image](https://user-images.githubusercontent.com/62988428/215338789-b7ec1928-8bcf-4f53-9d78-85bccbf4aad3.png)

**Comment by FranklinYu** [comment] 2023-04-04 05:10
This is duplicate of #1695.

**Closed** 2023-05-04 04:58 UTC
Labels: bug
